controller_manager:
  ros__parameters:
    update_rate: 225 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController


joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - j0
      - j1
      - j2
      - j3

    state_publish_rate: 200.0   
    action_monitor_rate: 20.0 

    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0


position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3